//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolizasModelContainer : DbContext
    {
        public PolizasModelContainer()
            : base("name=PolizasModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Poliza> PolizaSet { get; set; }
        public virtual DbSet<Usuarios> UsuariosSet { get; set; }
        public virtual DbSet<Roles> RolesSet { get; set; }
        public virtual DbSet<Cliente> ClienteSet { get; set; }
    }
}
