//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        public int NumPoliza { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaVigencia { get; set; }
        public int cobertura { get; set; }
        public string observaciones { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
